package io.github.adamw7.tools.grpc;

import java.util.concurrent.TimeUnit;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import io.github.adamw7.tools.grpc.builders.HelloRequestBuilder;
import io.github.adamw7.tools.grpc.proto.GreeterGrpc;
import io.github.adamw7.tools.grpc.proto.HelloReply;
import io.github.adamw7.tools.grpc.proto.HelloRequest;
import io.grpc.Grpc;
import io.grpc.InsecureChannelCredentials;
import io.grpc.ManagedChannel;

/**
 * Runnable gRPC client that builds its request with the compile-time-safe
 * {@link HelloRequestBuilder} generated by the protogen-maven-plugin and calls
 * the {@link GreeterServer}.
 */
public class GreeterClient {

	private static final Logger log = LogManager.getLogger(GreeterClient.class.getName());
	private static final String DEFAULT_TARGET = "localhost:50051";

	public static void main(String[] args) throws InterruptedException {
		String name = args.length > 0 ? args[0] : "World";
		ManagedChannel channel = Grpc.newChannelBuilder(DEFAULT_TARGET, InsecureChannelCredentials.create()).build();
		try {
			GreeterGrpc.GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel);
			HelloRequest request = new HelloRequestBuilder().setName(name).build();
			HelloReply reply = stub.sayHello(request);
			log.info("Greeting: {}", reply.getMessage());
		} finally {
			channel.shutdownNow().awaitTermination(5, TimeUnit.SECONDS);
		}
	}
}
