package io.github.adamw7.tools.grpc;

import java.util.concurrent.TimeUnit;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import io.github.adamw7.tools.grpc.builders.AddressBuilder;
import io.github.adamw7.tools.grpc.builders.AddressOptionalIfc;
import io.github.adamw7.tools.grpc.builders.HelloRequestBuilder;
import io.github.adamw7.tools.grpc.builders.PersonBuilder;
import io.github.adamw7.tools.grpc.builders.PersonOptionalIfc;
import io.github.adamw7.tools.grpc.proto.Address;
import io.github.adamw7.tools.grpc.proto.GreeterGrpc;
import io.github.adamw7.tools.grpc.proto.HelloReply;
import io.github.adamw7.tools.grpc.proto.HelloRequest;
import io.grpc.Grpc;
import io.grpc.InsecureChannelCredentials;
import io.grpc.ManagedChannel;
import io.grpc.StatusRuntimeException;

/**
 * Runnable gRPC client that assembles its request through the compile-time-safe
 * builders generated by the protogen-maven-plugin, walking the full
 * {@code HelloRequest -> Person -> Address} chain that this module exists to
 * demonstrate, then calls the {@link GreeterServer}.
 *
 * <p>Usage: {@code name [title [city [country]]]}. Only {@code name} is
 * required; supplying a city adds the nested {@link Address}, and a country
 * enriches it further.
 */
public class GreeterClient {

	private static final Logger log = LogManager.getLogger(GreeterClient.class.getName());
	private static final String DEFAULT_TARGET = "localhost:50051";
	private static final long DEADLINE_SECONDS = 5;

	public static void main(String[] args) throws InterruptedException {
		ManagedChannel channel = Grpc.newChannelBuilder(DEFAULT_TARGET, InsecureChannelCredentials.create()).build();
		try {
			greet(channel, buildRequest(args));
		} finally {
			channel.shutdownNow().awaitTermination(DEADLINE_SECONDS, TimeUnit.SECONDS);
		}
	}

	private static void greet(ManagedChannel channel, HelloRequest request) {
		GreeterGrpc.GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel)
				.withDeadlineAfter(DEADLINE_SECONDS, TimeUnit.SECONDS);
		try {
			HelloReply reply = stub.sayHello(request);
			log.info("Greeting: {}", reply.getMessage());
		} catch (StatusRuntimeException e) {
			log.error("RPC failed with status {}", e.getStatus());
		}
	}

	private static HelloRequest buildRequest(String[] args) {
		String name = args.length > 0 ? args[0] : "World";
		PersonOptionalIfc person = new PersonBuilder().setName(name);
		if (args.length > 1) {
			person = person.setTitle(args[1]);
		}
		if (args.length > 2) {
			person = person.setAddress(buildAddress(args));
		}
		return new HelloRequestBuilder().setPerson(person.build()).build();
	}

	private static Address buildAddress(String[] args) {
		AddressOptionalIfc address = new AddressBuilder().setCity(args[2]);
		if (args.length > 3) {
			address = address.setCountry(args[3]);
		}
		return address.build();
	}
}
