package io.github.adamw7.tools.grpc;

import io.github.adamw7.tools.grpc.builders.HelloReplyBuilder;
import io.github.adamw7.tools.grpc.proto.Address;
import io.github.adamw7.tools.grpc.proto.GreeterGrpc;
import io.github.adamw7.tools.grpc.proto.HelloReply;
import io.github.adamw7.tools.grpc.proto.HelloRequest;
import io.github.adamw7.tools.grpc.proto.Person;
import io.grpc.stub.StreamObserver;

/**
 * gRPC service implementation that builds its response with the compile-time-safe
 * {@link HelloReplyBuilder} generated by the protogen-maven-plugin. The builder
 * forces the required {@code message} field to be set before {@code build()}.
 */
public class GreeterServiceImpl extends GreeterGrpc.GreeterImplBase {

	@Override
	public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
		HelloReply reply = new HelloReplyBuilder().setMessage(greetingFor(request)).build();
		responseObserver.onNext(reply);
		responseObserver.onCompleted();
	}

	private String greetingFor(HelloRequest request) {
		Person person = request.getPerson();
		return "Hello, " + titlePrefix(person) + person.getName() + locationSuffix(person) + "!";
	}

	private String titlePrefix(Person person) {
		return person.hasTitle() ? person.getTitle() + " " : "";
	}

	private String locationSuffix(Person person) {
		return person.hasAddress() ? " from " + place(person.getAddress()) : "";
	}

	private String place(Address address) {
		return address.hasCountry() ? address.getCity() + ", " + address.getCountry() : address.getCity();
	}
}
