package io.github.adamw7.tools.grpc;

import io.github.adamw7.tools.grpc.builders.HelloReplyBuilder;
import io.github.adamw7.tools.grpc.proto.GreeterGrpc;
import io.github.adamw7.tools.grpc.proto.HelloReply;
import io.github.adamw7.tools.grpc.proto.HelloRequest;
import io.grpc.stub.StreamObserver;

/**
 * gRPC service implementation that builds its response with the compile-time-safe
 * {@link HelloReplyBuilder} generated by the protogen-maven-plugin. The builder
 * forces the required {@code message} field to be set before {@code build()}.
 */
public class GreeterServiceImpl extends GreeterGrpc.GreeterImplBase {

	@Override
	public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
		HelloReply reply = new HelloReplyBuilder().setMessage(greetingFor(request)).build();
		responseObserver.onNext(reply);
		responseObserver.onCompleted();
	}

	private String greetingFor(HelloRequest request) {
		return "Hello, " + titlePrefix(request) + request.getName() + "!";
	}

	private String titlePrefix(HelloRequest request) {
		return request.hasTitle() ? request.getTitle() + " " : "";
	}
}
