package io.github.adamw7.tools.grpc;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.IOException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import io.github.adamw7.tools.grpc.builders.AddressBuilder;
import io.github.adamw7.tools.grpc.builders.HelloRequestBuilder;
import io.github.adamw7.tools.grpc.builders.PersonBuilder;
import io.github.adamw7.tools.grpc.proto.Address;
import io.github.adamw7.tools.grpc.proto.GreeterGrpc;
import io.github.adamw7.tools.grpc.proto.HelloReply;
import io.github.adamw7.tools.grpc.proto.HelloRequest;
import io.github.adamw7.tools.grpc.proto.Person;
import io.grpc.ManagedChannel;
import io.grpc.Server;
import io.grpc.inprocess.InProcessChannelBuilder;
import io.grpc.inprocess.InProcessServerBuilder;

/**
 * End-to-end example wiring an in-process gRPC server and client. Both the
 * request and the response are constructed through the compile-time-safe
 * builders generated by the protogen-maven-plugin from {@code greeter.proto}.
 */
public class GreeterExampleTest {

	private Server server;
	private ManagedChannel channel;
	private GreeterGrpc.GreeterBlockingStub stub;

	@BeforeEach
	public void setUp() throws IOException {
		String serverName = InProcessServerBuilder.generateName();
		server = InProcessServerBuilder.forName(serverName).directExecutor()
				.addService(new GreeterServiceImpl()).build().start();
		channel = InProcessChannelBuilder.forName(serverName).directExecutor().build();
		stub = GreeterGrpc.newBlockingStub(channel);
	}

	@AfterEach
	public void tearDown() {
		channel.shutdownNow();
		server.shutdownNow();
	}

	@Test
	public void greetsUsingGeneratedRequestBuilder() {
		Person person = new PersonBuilder().setName("World").build();
		HelloRequest request = new HelloRequestBuilder().setPerson(person).build();
		HelloReply reply = stub.sayHello(request);
		assertNotNull(reply);
		assertEquals("Hello, World!", reply.getMessage());
	}

	@Test
	public void greetsWithOptionalTitle() {
		Person person = new PersonBuilder().setName("Smith").setTitle("Dr.").build();
		HelloRequest request = new HelloRequestBuilder().setPerson(person).build();
		HelloReply reply = stub.sayHello(request);
		assertEquals("Hello, Dr. Smith!", reply.getMessage());
	}

	@Test
	public void greetsWithNestedAddress() {
		Address address = new AddressBuilder().setCity("London").setCountry("UK").build();
		Person person = new PersonBuilder().setName("Smith").setTitle("Dr.").setAddress(address).build();
		HelloRequest request = new HelloRequestBuilder().setPerson(person).build();
		HelloReply reply = stub.sayHello(request);
		assertEquals("Hello, Dr. Smith from London!", reply.getMessage());
	}
}
