spring.application.name=context-engineering-mcp
server.port=8082
spring.main.allow-bean-definition-overriding=true

logging.level.root=INFO
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.io.modelcontextprotocol=INFO
logging.level.io.github.adamw7.context=INFO
