package io.github.adamw7.tools.code;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;

import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.apache.maven.plugin.AbstractMojo;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 * Verifies that the artifact produced by this module is a correct Maven plugin
 * by validating the descriptor generated by {@code maven-plugin-plugin}
 * ({@code META-INF/maven/plugin.xml}). The descriptor is what Maven reads when a
 * consumer runs the plugin, so a malformed or incomplete descriptor means a broken
 * plugin even when every unit test passes.
 */
public class PluginDescriptorTest {

	private static final String DESCRIPTOR = "/META-INF/maven/plugin.xml";
	private static final String EXPECTED_GOAL_PREFIX = "protogen";
	private static final String EXPECTED_GOAL = "code-generator";
	private static final String EXPECTED_PHASE = "generate-sources";
	private static final String EXPECTED_IMPLEMENTATION = "io.github.adamw7.tools.code.CodeMojo";
	private static final String INHERITED_DESCRIPTION_PREFIX = "Parent pom";
	private static final List<String> REQUIRED_PARAMETERS = List.of("generatedSourcesDir", "outputpackage", "pkgs");

	private static Document descriptor;

	@BeforeAll
	public static void loadDescriptor() {
		descriptor = parse(openDescriptor());
	}

	@Test
	public void descriptorDeclaresGoalPrefix() {
		assertEquals(EXPECTED_GOAL_PREFIX, textOfFirst(descriptor.getDocumentElement(), "goalPrefix"));
	}

	@Test
	public void descriptorHasOwnDescription() {
		String description = textOfFirst(descriptor.getDocumentElement(), "description");
		assertNotNull(description, "Plugin descriptor declares no description");
		assertFalse(description.isBlank(), "Plugin description must not be blank");
		assertFalse(description.startsWith(INHERITED_DESCRIPTION_PREFIX),
				"Plugin must declare its own description instead of inheriting the parent pom's");
	}

	@Test
	public void descriptorDeclaresExactlyOneMojo() {
		assertEquals(1, mojos().size());
	}

	@Test
	public void mojoDeclaresGoal() {
		assertEquals(EXPECTED_GOAL, textOfFirst(singleMojo(), "goal"));
	}

	@Test
	public void mojoBindsToGenerateSourcesPhase() {
		assertEquals(EXPECTED_PHASE, textOfFirst(singleMojo(), "phase"));
	}

	@Test
	public void mojoImplementationExistsAndIsAMojo() {
		String implementation = textOfFirst(singleMojo(), "implementation");
		assertEquals(EXPECTED_IMPLEMENTATION, implementation);
		Class<?> implementationClass = loadClass(implementation);
		assertTrue(AbstractMojo.class.isAssignableFrom(implementationClass),
				implementation + " must extend AbstractMojo");
	}

	@Test
	public void requiresProjectForClasspathResolution() {
		assertEquals("true", textOfFirst(singleMojo(), "requiresProject"));
	}

	@Test
	public void allDocumentedParametersAreRequired() {
		List<Element> parameters = parameters();
		assertAll(REQUIRED_PARAMETERS.stream()
				.map(name -> () -> assertParameterIsRequired(parameters, name)));
	}

	private void assertParameterIsRequired(List<Element> parameters, String name) {
		Element parameter = findParameter(parameters, name);
		assertNotNull(parameter, "Missing parameter '" + name + "' in plugin descriptor");
		assertEquals("true", textOfFirst(parameter, "required"), "Parameter '" + name + "' must be required");
	}

	private Element findParameter(List<Element> parameters, String name) {
		return parameters.stream()
				.filter(parameter -> name.equals(textOfFirst(parameter, "name")))
				.findFirst()
				.orElse(null);
	}

	private List<Element> parameters() {
		Element parametersElement = firstChildElement(singleMojo(), "parameters");
		assertNotNull(parametersElement, "Mojo declares no parameters");
		return childElements(parametersElement, "parameter");
	}

	private Element singleMojo() {
		return mojos().getFirst();
	}

	private List<Element> mojos() {
		Element mojosElement = firstChildElement(descriptor.getDocumentElement(), "mojos");
		assertNotNull(mojosElement, "Descriptor declares no mojos");
		return childElements(mojosElement, "mojo");
	}

	private static String textOfFirst(Element parent, String tag) {
		Element child = firstChildElement(parent, tag);
		return child == null ? null : child.getTextContent().trim();
	}

	private static Element firstChildElement(Element parent, String tag) {
		List<Element> children = childElements(parent, tag);
		return children.isEmpty() ? null : children.getFirst();
	}

	private static List<Element> childElements(Element parent, String tag) {
		List<Element> elements = new ArrayList<>();
		NodeList children = parent.getChildNodes();
		for (int i = 0; i < children.getLength(); i++) {
			Node node = children.item(i);
			boolean matches = node.getNodeType() == Node.ELEMENT_NODE && tag.equals(node.getNodeName());
			if (matches) {
				elements.add((Element) node);
			}
		}
		return elements;
	}

	private static Class<?> loadClass(String name) {
		try {
			return Class.forName(name);
		} catch (ClassNotFoundException e) {
			fail("Mojo implementation class not found on the classpath: " + name);
			throw new IllegalStateException(e);
		}
	}

	private static InputStream openDescriptor() {
		InputStream stream = PluginDescriptorTest.class.getResourceAsStream(DESCRIPTOR);
		assertNotNull(stream, "Plugin descriptor " + DESCRIPTOR
				+ " not found on the classpath. Run 'mvn process-classes' to generate it.");
		return stream;
	}

	private static Document parse(InputStream stream) {
		try (stream) {
			return newSecureBuilder().parse(stream);
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		} catch (SAXException e) {
			fail("Plugin descriptor is not well-formed XML: " + e.getMessage());
			throw new IllegalStateException(e);
		}
	}

	private static DocumentBuilder newSecureBuilder() {
		try {
			DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
			factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
			return factory.newDocumentBuilder();
		} catch (ParserConfigurationException e) {
			throw new IllegalStateException(e);
		}
	}
}
